# Generated by Django 3.2.13 on 2023-08-23 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0002_alter_package_package_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='status',
            field=models.CharField(choices=[('closed', 'Closed'), ('open', 'Open'), ('draft', 'Draft'), ('publish', 'Published')], default='draft', max_length=10),
        ),
    ]
