# Generated by Django 3.2.13 on 2023-08-23 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0003_alter_package_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='status',
            field=models.CharField(choices=[('closed', 'Closed'), ('open', 'Open'), ('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10),
        ),
    ]
