# Generated by Django 3.2.13 on 2023-09-09 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0004_alter_package_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='listed',
            field=models.CharField(choices=[('L', 'Listed'), ('Del', 'Delisted')], default='Del', max_length=3),
        ),
        migrations.AlterField(
            model_name='package',
            name='category',
            field=models.CharField(choices=[('apartment', 'APARTMENT'), ('duplex', 'Duplex'), ('hostel', 'Hostel'), ('land', 'Land')], default='land', max_length=20),
        ),
        migrations.AlterField(
            model_name='package',
            name='status',
            field=models.CharField(choices=[('closed', 'Closed'), ('open', 'Open')], default='open', max_length=10),
        ),
    ]
