# Generated by Django 3.2.13 on 2023-09-09 13:56

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import package.models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0004_auto_20230706_1340'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('package', '0005_auto_20230909_1453'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('image', models.FileField(blank=True, null=True, upload_to=package.models.upload_image_path)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=15)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField()),
                ('area', models.DecimalField(decimal_places=2, max_digits=10)),
                ('location', models.CharField(max_length=250)),
                ('property_key', models.CharField(blank=True, max_length=30, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('featured', models.BooleanField(default=False)),
                ('listed', models.CharField(choices=[('L', 'Listed'), ('Del', 'Delisted')], default='Del', max_length=3)),
                ('category', models.CharField(choices=[('apartment', 'APARTMENT'), ('duplex', 'Duplex'), ('hostel', 'Hostel'), ('land', 'Land')], default='land', max_length=20)),
                ('status', models.CharField(choices=[('closed', 'Closed'), ('open', 'Open')], default='open', max_length=10)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-publish',),
            },
        ),
    ]
