# Generated by Django 3.2.13 on 2024-01-03 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consult', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='number_team_members',
            field=models.CharField(choices=[('1', 'Personal Consultation'), ('2', 'Two'), ('4', 'Three'), ('more than 3', 'More than 3')], default='1', max_length=15),
        ),
    ]
