# Generated by Django 3.2.13 on 2023-11-12 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_remove_topic_completed'),
        ('students', '0002_student_progress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='progress',
        ),
        migrations.AddField(
            model_name='student',
            name='completed_topics',
            field=models.ManyToManyField(blank=True, related_name='completed_by', to='course.Topic'),
        ),
    ]
