# Generated by Django 3.2.13 on 2024-01-12 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0013_alter_objective_options'),
        ('students', '0003_auto_20231112_0751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='completed_topics',
        ),
        migrations.AddField(
            model_name='student',
            name='completed_modules',
            field=models.ManyToManyField(blank=True, related_name='completed_by', to='course.Module'),
        ),
    ]
