# Generated by Django 3.2.13 on 2024-01-18 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_auto_20240112_1317'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='completed_modules',
            new_name='completed_topics',
        ),
    ]
