# Generated by Django 3.2.13 on 2024-01-21 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0017_completedtopic'),
        ('students', '0005_rename_completed_modules_student_completed_topics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='enrolled_courses',
            field=models.ManyToManyField(blank=True, related_name='enrolled_students', to='course.Course'),
        ),
    ]
