# Generated by Django 3.2.13 on 2024-01-22 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0017_completedtopic'),
        ('students', '0006_alter_student_enrolled_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='completed_topics',
            field=models.ManyToManyField(blank=True, related_name='completed_by', to='course.Topic'),
        ),
    ]
