# Generated by Django 3.2.13 on 2023-11-12 04:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0003_auto_20231111_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='completed_by',
            field=models.ManyToManyField(blank=True, related_name='completed_topics', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='topic',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course'),
        ),
    ]
