# Generated by Django 3.2.13 on 2023-11-12 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_alter_topic_completed_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='completed_by',
        ),
        migrations.AddField(
            model_name='topic',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
