# Generated by Django 3.2.13 on 2023-11-12 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_auto_20231112_0715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='completed',
        ),
    ]
