# Generated by Django 3.2.13 on 2024-01-01 13:34

import course.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_remove_topic_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=course.models.upload_image_path),
        ),
    ]
