# Generated by Django 3.2.13 on 2024-01-12 14:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0015_alter_objective_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objective',
            name='featured',
        ),
        migrations.RemoveField(
            model_name='objective',
            name='premium',
        ),
        migrations.RemoveField(
            model_name='objective',
            name='students',
        ),
        migrations.AddField(
            model_name='course',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='premium',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='courses_joined', to=settings.AUTH_USER_MODEL),
        ),
    ]
