# Generated by Django 3.2.13 on 2023-08-25 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='id_referrer',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
