# Generated by Django 3.2.13 on 2024-01-06 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20240106_1442'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='sender',
            new_name='email_address',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='cc_myself',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='phone',
        ),
    ]
