# Generated by Django 3.2.13 on 2023-10-26 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(blank=True, max_length=50, null=True)),
                ('slot', models.IntegerField(default=1)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('payment_option', models.CharField(choices=[('one_time_payment', 'One Time Payment'), ('installmental', 'Installmental')], default='one_time_payment', max_length=50)),
                ('payment_reference', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('created', 'Created'), ('paid', 'Paid'), ('refunded', 'Refunded'), ('failed', 'Failed')], default='created', max_length=50)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
