# Generated by Django 3.2.13 on 2023-08-23 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='slot',
            field=models.IntegerField(default=1),
        ),
    ]
