# Generated by Django 3.2.13 on 2023-10-26 12:27

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dividend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            managers=[
                ('income', django.db.models.manager.Manager()),
            ],
        ),
    ]
