# Generated by Django 3.2.13 on 2023-09-05 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dividend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dividend',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
    ]
