# Generated by Django 3.2.13 on 2023-09-07 07:55

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('dividend', '0002_alter_dividend_amount'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='dividend',
            managers=[
                ('income', django.db.models.manager.Manager()),
            ],
        ),
    ]
