# Generated by Django 3.2.13 on 2023-09-07 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dividend', '0004_log'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Log',
        ),
    ]
