# Generated by Django 3.2.13 on 2023-09-09 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dividend', '0006_dividend_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dividend',
            name='user',
        ),
    ]
